CREATE TABLE custom_pages (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
custom_url VARCHAR(150) UNIQUE NOT NULL,
content TEXT NOT NULL,
author_id UUID REFERENCES users(id) ON DELETE SET NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
