CREATE TABLE comments (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
news_id UUID NOT NULL REFERENCES news(id) ON DELETE CASCADE,
name VARCHAR(100) DEFAULT 'Anonymous',
comment TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
